<?php

/**
 * @file
 * FlowDrop_job module file.
 */

declare(strict_types=1);

/**
 * @file
 * Provides a flowdrop job entity type.
 */

use Drupal\flowdrop_job\FlowDropJobInterface;
use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function flowdrop_job_theme(): array {
  return [
    'flowdrop_job' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for flowdrop job templates.
 *
 * Default template: flowdrop-job.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the flowdrop
 *     job information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_flowdrop_job(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function flowdrop_job_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish flowdrop jobs.
      $storage = \Drupal::entityTypeManager()->getStorage('flowdrop_job');
      $flowdrop_job_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($flowdrop_job_ids) as $flowdrop_job) {
        if ($flowdrop_job instanceof FlowDropJobInterface) {
          $flowdrop_job->set('status', FALSE)->save();
        }
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize flowdrop jobs.
      $storage = \Drupal::entityTypeManager()->getStorage('flowdrop_job');
      $flowdrop_job_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($flowdrop_job_ids) as $flowdrop_job) {
        if ($flowdrop_job instanceof FlowDropJobInterface) {
          $flowdrop_job->setOwnerId(0)->save();
        }
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function flowdrop_job_user_predelete(UserInterface $account): void {
  // Delete flowdrop jobs that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('flowdrop_job');
  $flowdrop_job_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($flowdrop_job_ids)
  );
}
