<?php

/**
 * @file
 * FlowDrop_pipeline module file.
 */

declare(strict_types=1);

/**
 * @file
 * Provides a flowdrop pipeline entity type.
 */

use Drupal\flowdrop_pipeline\Entity\FlowDropPipelineInterface;
use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function flowdrop_pipeline_theme(): array {
  return [
    'flowdrop_pipeline' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for flowdrop pipeline templates.
 *
 * Default template: flowdrop-pipeline.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the
 *     flowdrop pipeline information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_flowdrop_pipeline(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function flowdrop_pipeline_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish flowdrop pipelines.
      $storage = \Drupal::entityTypeManager()->getStorage('flowdrop_pipeline');
      $flowdrop_pipeline_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($flowdrop_pipeline_ids) as $flowdrop_pipeline) {
        if ($flowdrop_pipeline instanceof FlowDropPipelineInterface) {
          $flowdrop_pipeline->set('status', FALSE)->save();
        }
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize flowdrop pipelines.
      $storage = \Drupal::entityTypeManager()->getStorage('flowdrop_pipeline');
      $flowdrop_pipeline_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($flowdrop_pipeline_ids) as $flowdrop_pipeline) {
        if ($flowdrop_pipeline instanceof FlowDropPipelineInterface) {
          $flowdrop_pipeline->setOwnerId(0)->save();
        }
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function flowdrop_pipeline_user_predelete(UserInterface $account): void {
  // Delete flowdrop pipelines that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('flowdrop_pipeline');
  $flowdrop_pipeline_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($flowdrop_pipeline_ids)
  );
}
